### ISSUE TITLE
Lilypond export option in menus/toolbars

### ISSUE THREAD

**Issue by Whatang** [Whatang/DrumBurp#210]
There needs to be an option to export to Lilypond in the File menu, and from one of the toolbars.

**Comment by georgeraraujo** [comment]
Please bring this option back from v0.7a as per the [manual](https://whatang.org/manual/exporting/lilypond/).

**Comment by Whatang** [comment]
DB now uses the Lilypond preview tab to do exports. The manual needs updating, but I don't plan to bring back the toolbar option.
