### ISSUE TITLE
Fresh install v1.1 : "Failed to execute script DrumBurp"

### ISSUE THREAD

**Issue by MrHeadwar** [Whatang/DrumBurp#417]
Hi and thanks for DrumBurp. Although version 1.0 worked perfectly fine, a fresh install of v1.1 gives me the error message : "Failed to execute script DrumBurp", and the program is not started.

It's on a win 7 machine, french version.
Thanks.

**Comment by Whatang** [comment]
Hi, can you please try the [new release of v1.1.1](https://github.com/Whatang/DrumBurp/releases/tag/1.1.1)?

One of the packages that DB depends on was importing something in a way that the package builder could not pick up. That should now be fixed.

**Comment by MrHeadwar** [comment]
1.1.1 works flawlessly ! Thanks a lot.
